/* Formatted on 8/7/2018 3:48:23 PM (QP5 v5.300) */
CREATE TABLE HYANG.COUNTRIES
(
    COUNTRY_ID     CHAR (2 BYTE) CONSTRAINT COUNTRY_ID_NN NOT NULL,
    COUNTRY_NAME   VARCHAR2 (40 BYTE),
    REGION_ID      NUMBER,
    CONSTRAINT COUNTRY_C_ID_PK PRIMARY KEY (COUNTRY_ID) ENABLE VALIDATE
);


CREATE TABLE HYANG.DEPARTMENTS
(
    DEPARTMENT_ID     NUMBER (4) PRIMARY KEY,
    DEPARTMENT_NAME   VARCHAR2 (30 BYTE) CONSTRAINT DEPT_NAME_NN NOT NULL,
    MANAGER_ID        NUMBER (6),
    LOCATION_ID       NUMBER (4)
);


CREATE TABLE HYANG.EMPLOYEES
(
    EMPLOYEE_ID      NUMBER (6) PRIMARY KEY,
    FIRST_NAME       VARCHAR2 (20 BYTE),
    LAST_NAME        VARCHAR2 (25 BYTE) CONSTRAINT EMP_LAST_NAME_NN NOT NULL,
    EMAIL            VARCHAR2 (25 BYTE) CONSTRAINT EMP_EMAIL_NN NOT NULL,
    PHONE_NUMBER     VARCHAR2 (20 BYTE),
    HIRE_DATE        DATE CONSTRAINT EMP_HIRE_DATE_NN NOT NULL,
    JOB_ID           VARCHAR2 (10 BYTE) CONSTRAINT EMP_JOB_NN NOT NULL,
    SALARY           NUMBER (8, 2),
    COMMISSION_PCT   NUMBER (2, 2),
    MANAGER_ID       NUMBER (6),
    DEPARTMENT_ID    NUMBER (4)
);


CREATE TABLE HYANG.JOBS
(
    JOB_ID       VARCHAR2 (10 BYTE) PRIMARY KEY,
    JOB_TITLE    VARCHAR2 (35 BYTE) CONSTRAINT JOB_TITLE_NN NOT NULL,
    MIN_SALARY   NUMBER (6),
    MAX_SALARY   NUMBER (6)
);


CREATE TABLE HYANG.JOB_HISTORY
(
    RECORD_ID       NUMBER PRIMARY KEY,
    EMPLOYEE_ID     NUMBER (6) CONSTRAINT JHIST_EMPLOYEE_NN NOT NULL,
    START_DATE      DATE CONSTRAINT JHIST_START_DATE_NN NOT NULL,
    END_DATE        DATE CONSTRAINT JHIST_END_DATE_NN NOT NULL,
    JOB_ID          VARCHAR2 (10 BYTE) CONSTRAINT JHIST_JOB_NN NOT NULL,
    DEPARTMENT_ID   NUMBER (4)
);


CREATE TABLE HYANG.LOCATIONS
(
    LOCATION_ID      NUMBER (4) PRIMARY KEY,
    STREET_ADDRESS   VARCHAR2 (40 BYTE),
    POSTAL_CODE      VARCHAR2 (12 BYTE),
    CITY             VARCHAR2 (30 BYTE) CONSTRAINT LOC_CITY_NN NOT NULL,
    STATE_PROVINCE   VARCHAR2 (25 BYTE),
    COUNTRY_ID       CHAR (2 BYTE)
);


CREATE TABLE HYANG.REGIONS
(
    REGION_ID     NUMBER PRIMARY KEY,
    REGION_NAME   VARCHAR2 (25 BYTE)
);